[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solanaday = "MzCmSBr1L3gyFMKvK2QK9CriD5sgFKzgUrMphi79rP1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
